// END POINTS
export enum URLz{
  // DROP DOWNS
  BG='businessGroup',
  LE='legalEntity',
  OU='operatingUnit',
  OU_CUSTOM='ouCustomization',
  SU="subUnit",
  BRANCH='branch',
  COST5='costSix',
  FUND_CATEGORY='fundCategory',
  // DEPTT='majlis',
  MAJLIS='majlis',
  LOCATION='location',
  PURPOSE='purpose',
  ORG_SYSTEM='organization_system',
  SYSTEM='system',
  USER_ID='userforDonor',// Query
  COUNTRY='country',
  STATE='state',
  CITY='city',
  ROLES='roles',
  MODULE_LIST = 'moduleList',
  PARAMETER='parameters',
  // TREE VIEW
  ANALYSIS_TREE_GET= 'get_analysis',
  ANALYSIS_TREE_POST= 'add_permission',
  TREE_VIEW_UNKNOWN= '',
  // COMPONENTS LIST
  ADVANCE_DONOR = 'advanceDonorSetup',
  ADMIN_USER = '',
  ADMIN_ALLOW = '',
  BOX_PRE_SELL = '',
  BOX_VENDOR = '',
  BOX_RECEIVE = '',
  BASTA_CAT='bastaCategory',
  BASTA_SUB_CAT='bastaSubCategory',
  ADD_BASIC_INFO='user',
  USER_LIST='users',
  PERSONAL_INFO='personal_info',
  ADDITIONAL_INFO = 'additional_info',
  DONOR='donor',
  DONOR_T='donorType',
  COLLECTOR_DONOR='collector',
  CHECK_USER_EXIST = 'check_user',
  DONATION_S_T='donationSubType',
  DONATION_T='donationType',
  DONATION_OPT='purpose',
  PLACE='natureOfPlace',
  EVENT='event',
  ORG='organization',
  CELL_MASTER = 'donationCellMaster',
  E_RASEED_BANK_DEPOSIT = 'eRaseedBankDeposit'
}
